# Generated by Django 2.1.7 on 2019-11-19 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_activo_fijo', models.CharField(max_length=100, null=True)),
                ('codigo_activo_fijo', models.IntegerField(null=True)),
                ('costo_activo_fijo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad_activo_fijo', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_caja', models.CharField(max_length=100, null=True)),
                ('saldo_caja', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_creado_caja', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardexCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('numero_pedido', models.IntegerField(null=True)),
                ('fecha_creado_cardex_caja', models.DateField(auto_now_add=True, null=True)),
                ('Caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, null=True)),
                ('apellido_cliente', models.CharField(max_length=100, null=True)),
                ('direccion_cliente', models.CharField(max_length=100, null=True)),
                ('telefono_cliente', models.IntegerField(null=True)),
                ('email_cliente', models.EmailField(max_length=125)),
                ('nit_cliente', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTrasladoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_detalle_traslado_producto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DominioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado_pedido', models.DateField(auto_now_add=True, null=True)),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_pedido', models.IntegerField(null=True)),
                ('Caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Caja')),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Cliente')),
                ('Documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=225, null=True)),
                ('codigo_producto', models.IntegerField(null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad_producto', models.IntegerField(null=True)),
                ('estado_producto', models.BooleanField(default=True, null=True)),
                ('fecha_creado', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificado', models.DateField(blank=True, null=True)),
                ('fecha_eliminado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100, null=True)),
                ('direccion_sucursal', models.CharField(max_length=100, null=True)),
                ('telefono_sucursal', models.IntegerField(null=True)),
                ('estado_sucursal', models.BooleanField(default=True, null=True)),
                ('Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Ciudad')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo_activo_fijo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo_producto', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Totales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('numero_factura', models.IntegerField(null=True, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traslado', models.DateField(null=True)),
                ('fecha_creado_traslado', models.DateField(auto_now_add=True, null=True)),
                ('Sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trasladoproducto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, null=True)),
                ('apellido_usuario', models.CharField(max_length=100, null=True)),
                ('telefono_usuario', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('estadoProfile', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='TipoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dominiousuario',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='dominiousuario',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalletrasladoproducto',
            name='Producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Producto'),
        ),
        migrations.AddField(
            model_name='detalletrasladoproducto',
            name='TrasladoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.TrasladoProducto'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='Pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='Producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='cardexcaja',
            name='Pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Pedido'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Documento'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.Sucursal'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='TipoActivoFijo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfarmaceutica.TipoActivoFijo'),
        ),
    ]
